config/routes.rb
Husna::Application.routes.draw do
  devise_for :users
  resources :translations

  root "welcome#index"
  get '/translate' => 'welcome#translate'

end

app/models/translation.rb
class Translation < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wordtranslation.rb
class Wordtranslation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @translation }
      else
        format.html { render action: 'new' }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:punjabi, :urdu)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_action :verify_authenticity_token
  def index
	
  end

  def translate
	@punjabiSentence = params[:punjabiAaala]
	@punjabiWords = @punjabiSentence.strip.split(" ")
	@noOfWords = @punjabiWords.length - 1
			
	@urduWords = []
       # @urduLetters = []

	for i in 0..@noOfWords
		@urduObj = Translation.where(punjabi: @punjabiWords[i]).first
		if @urduObj 		
		  @urduWords << @urduObj.urdu
		else 
		  @urduWords << "translation-not-found"
		end
   	end 
			#for j in 0..@punjabiLength
			##	@urduobj = Translation.where(punjabi: @noOfLetters[j]).first.inspect
			#	@urduLetters << @urduobj.urdu
			#end			
				
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Husna</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<%= yield %>

</body>
</html>

app/views/translations/_form.html.erb
<%= form_for(@translation) do |f| %>
  <% if @translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% @translation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :punjabi %><br>
    <%= f.text_area :punjabi %>
  </div>
  <div class="field">
    <%= f.label :urdu %><br>
    <%= f.text_area :urdu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>gt

app/views/translations/edit.html.erb
<h1>Editing translation</h1>

<%= render 'form' %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Listing translations</h1>

<table>
  <thead>
    <tr>
      <th>Punjabi</th>
      <th>Urdu</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.punjabi %></td>
        <td><%= translation.urdu %></td>
        <td><%= link_to 'Show', translation %></td>
        <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
        <td><%= link_to 'Destroy', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Translation', new_translation_path %>

app/views/translations/new.html.erb
<h1>New translation</h1>

<%= render 'form' %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Punjabi:</strong>
  <%= @translation.punjabi %>
</p>

<p>
  <strong>Urdu:</strong>
  <%= @translation.urdu %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>

app/views/welcome/index.html.erb
 <html lang="en">
	<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no">
<meta name="google-site-verification" content="osQ2Kp6S6VqE_VZ8Z_43eCYzBpjDII9URj-URIlbKIw">
<script>
function insertTextInInputValue(buttonValueIs){
             var inputElementIs = document.getElementById("psearch");
            inputElementIs.value = inputElementIs.value + buttonValueIs;
        }
function eraseText() {
    var value = document.getElementById("psearch").value;
    document.getElementById("psearch").value = value.substr(0, value.length - 1);
}


</script>	 

</head>
	    <header> 
		<h1> Husna </h1>
                       <div id ="signupandlogin">
                        <% if user_signed_in? %>
 				 Logged in as <strong><%= current_user.email %></strong>.
				 link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
                          
 		             <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
 		       	     <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
         		   
                        <% end %>
  		 </div>
	    </header>	    
       	    <section class="container">
                     
                <form action="/translate" method="get">
			<div class="punjabi-area area"> 
				<textarea id ="psearch" class="psearch" name="punjabiAaala" id="first">Write in Punjabi Here</textarea> 
			</div>
			<div class="urdu-area area">
	                	<textarea class="usearch" name="urduAaala" id="second">Expect Urdu Here</textarea>
			</div>
			<div class="btn-area">
				<input type="submit" class="submit" name="translateKar" value="Translate"/>
			</div>
		</form>
	
		<style>
         #keyboard{
                  margin-top:20px;
                  display:inline-block;

}
      	 button{

		height:32px;
		width:35px;
		background-color:pink;
	       }
	.double{
		width:95px;
	       }
         </style>
	<body>	
             <div id="keyboard">
               <div class="next line">
		<button id="k" class="a" onclick="insertTextInInputValue('|');">
			<div class="original">|</div></button>
		<button id="k" class="a" onclick="insertTextInInputValue('੧');">
			<div class="original">੧</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੨');">
			<div class="original">੨</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੩');">
			<div class="original">੩</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੪');">
			<div class="original">੪</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੫');">
			<div class="original">੫</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੬');">
			<div class="original">੬</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੭');">
			<div class="original">੭</div></button>
		<button id=" k" class="a"onclick="insertTextInInputValue('੮');">
			<div class="original">੮</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੯');">
			<div class="original">੯</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੦');">
			<div class="original">੦</div></button>
		<button class ="double" onclick="insertTextInInputValue(' ');">
                        <div class ="original">SPACE</div></button>
 		<button class="double" id="clearbutton"  onclick="javascript:eraseText();">
                        <div class ="original">BACKSPACE</div></button>	
	</div>	
	<div class="next line">			
		<button id="k" class="a" onclick="insertTextInInputValue('ੳ');">
		        <div class="original" >ੳ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਉ');">
			<div class="original">ਉ</div></button>
                 <button id="k" class="a"onclick="insertTextInInputValue('ਊ');">
			<div class="original">ਊ</div></button>
		<button id="k" class="a" onclick="insertTextInInputValue('ਓ');">
			<div class="original">ਓ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਅ');">
			<div class="original">ਅ </div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਔ');">
			<div class="original">ਔ</div></button>		
		<button id="k" class="a"onclick="insertTextInInputValue('ਐ');">
			<div class="original">ਐ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਆ');">
			<div class="original">ਆ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੲ');">
		        <div class="original" >ੲ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਇ ');">
			<div class="original">ਇ </div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਈ');">
			<div class="original">ਈ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਏ');">
			<div class="original"> ਏ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਸ');">
			<div class="original">ਸ </div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਸ਼');">
			<div class="original">ਸ਼ </div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਹ');">
			<div class="original">ਹ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਕ');">
			<div class="original"> ਕ</div></button>
	   </div>
	<div class="next line">		
		<button id="k" class="a"onclick="insertTextInInputValue('ਖ');">
			<div class="original">ਖ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਖ਼');">
			<div class="original">ਖ਼</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਗ');">
			<div class="original">ਗ</div></button>
			<button id="k" class="a"onclick="insertTextInInputValue('ਗ਼');">
			<div class="original">ਗ਼</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਘ');">
			<div class="original">ਘ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਙ');">
			<div class="original">ਙ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਚ');">
			<div class="original">ਚ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਛ');">
			<div class="original">ਛ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਜ');">
			<div class="original">ਜ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਜ਼');">
			<div class="original">ਜ਼</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਝ');">
			<div class="original">ਝ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਞ');">
			<div class="original">ਞ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਟ');">
			<div class="original">ਟ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਠ');">
			<div class="original">ਠ</div></button>
	   
		<button id="k" class="a" onclick="insertTextInInputValue('ਡ');">
			<div class="original">ਡ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਢ');">
			<div class="original">ਢ</div></button>
	</div>
	<div class="next line">	
		<button id="k" class="a"onclick="insertTextInInputValue('ਣ');">
			<div class="original">ਣ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਤ');">
			<div class="original">ਤ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਥ');">
			<div class="original">ਥ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਦ');">
			<div class="original">ਦ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਧ');">
			<div class="original">ਧ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਨ');">
			<div class="original">ਨ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਪ');">
			<div class="original">ਪ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਫ');">
			<div class="original">ਫ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਫ਼');">
			<div class="original">ਫ਼</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਬ');">
			<div class="original">ਬ</div></button>		
		<button id="k" class="a"onclick="insertTextInInputValue('ਭ');">
			<div class="original">ਭ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਮ');">
			<div class="original">ਮ</div></button>
	   
		<button id="k" class="a"onclick="insertTextInInputValue('ਯ');">
			<div class="original">ਯ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਰ');">
			<div class="original"> ਰ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਲ');">
			<div class="original">ਲ</div></button>	
			
		<button id="k" class="a"onclick="insertTextInInputValue('ਲ਼');">
			<div class="original">ਲ਼</div></button>
		</div>
	<div class="next line">	
		<button id="k" class="a"onclick="insertTextInInputValue('ਵ');">
			<div class="original">ਵ</div></button>
		<button id="k" class="original"onclick="insertTextInInputValue('ੜ');">
			<div class="original">ੜ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ਾ');">
			<div class="original">ਾ</div></button>
	         <button id="k" class="a"onclick="insertTextInInputValue('ਂ');">
			<div class="original">ਂ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ਿ');">
			<div class="original">ਿ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੀ');">
			<div class="original">ੀ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੇੇ');">
			<div class="original">ੇ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੈ');">
			<div class="original">ੈ</div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ੁ');">
			<div class="original">ੁ </div></button>	
		<button id="k" class="a"onclick="insertTextInInputValue('ੂ');">
			<div class="original">ੂ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੋ');">
			<div class="original">ੋ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੌ');">
			<div class="original">ੌ</div></button>
	 
	        <button id="k" class="a"onclick="insertTextInInputValue('ੱ');">
			<div class="original">ੱ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('ੰ');">
			<div class="original">ੰ</div></button>
		<button id="k" class="a"onclick="insertTextInInputValue('੍');">
			<div class="original">੍</div></button>		
		<button id="k" class="a"onclick="insertTextInInputValue('ਁ');">
			<div class="original">ਁ</div></button>			
 		
	   </div>
     </div>	


	    </section>

app/views/welcome/translate.html.erb
	
    <header> 
		<h1> Husna </h1>
		
	    </header>	    
       	    <section class="container">     
                <form action="/translate" method="get">
			
			<div class="punjabi-area area"> 
				<textarea class="psearch" name="punjabiAaala" id="first"><% @punjabiWords.each do |word| %><%= word %> <% end %></textarea> 
			</div>
			<div class="urdu-area area">
	                	<textarea class="usearch" dir="rtl" name="urduAaala" id="second"><% @urduWords.each do |word| %><%= word %> <% end %></textarea>
			</div>
			<div class="btn-area">
				<input type="submit" class="submit" name="translateKar" value="Translate"/>
			</div>
		</form>
	    </section>